#!/bin/bash
# record all ar commands

ROOTDIR=
if [ -z $ROOTDIR ]; then
	echo "error: no rootdir specified in $0"
	exit 1
fi

MAKEFILE_NAME=$ROOTDIR/Makefile.llvmir
LOG_NAME=$ROOTDIR/Makefile.llvmir.log
PWD=`pwd`

AR=/usr/bin/ar
LLVM_LINK=llvm-link

$AR $@
exit_status=$?

if [ $exit_status != 0 ]; then
	exit $?
fi

PARAMS=($@)
PARAMS[0]=-o	# command
OUTFILE=${PARAMS[1]}
OUTFILE=${OUTFILE/.a/.a.bc}
if [ "${#PARAMS[@]}" == "2" ]; then
	echo "touch $OUTFILE" >> $LOG_NAME
	touch $OUTFILE
	exit $exit_status
fi
INFILES=${PARAMS[@]}
INFILES=${INFILES//.o/.bc}
INFILES=${INFILES//.a/.a.bc}
PARAMS[1]=$OUTFILE

$LLVM_LINK $INFILES
echo "#$OUTFILE: $INFILES" >> $MAKEFILE_NAME
echo -e "#"\\\t"$LLVM_LINK $INFILES" >> $MAKEFILE_NAME
echo "" >> $MAKEFILE_NAME
echo "$LLVM_LINK $INFILES" >> $LOG_NAME

exit $exit_status
